/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const EffectScope: typeof import('vue').EffectScope
  const ElLink: typeof import('element-plus/es').ElLink
  const ElSpace: typeof import('element-plus/es').ElSpace
  const acceptHMRUpdate: typeof import('pinia').acceptHMRUpdate
  const commonAttrs: typeof import('./src/store/init.js').commonAttrs
  const computed: typeof import('vue').computed
  const createApp: typeof import('vue').createApp
  const createPinia: typeof import('pinia').createPinia
  const customRef: typeof import('vue').customRef
  const defineAsyncComponent: typeof import('vue').defineAsyncComponent
  const defineComponent: typeof import('vue').defineComponent
  const defineStore: typeof import('pinia').defineStore
  const effectScope: typeof import('vue').effectScope
  const getActivePinia: typeof import('pinia').getActivePinia
  const getCurrentInstance: typeof import('vue').getCurrentInstance
  const getCurrentScope: typeof import('vue').getCurrentScope
  const getCurrentWatcher: typeof import('vue').getCurrentWatcher
  const h: typeof import('vue').h
  const inject: typeof import('vue').inject
  const isProxy: typeof import('vue').isProxy
  const isReactive: typeof import('vue').isReactive
  const isReadonly: typeof import('vue').isReadonly
  const isRef: typeof import('vue').isRef
  const isShallow: typeof import('vue').isShallow
  const mapActions: typeof import('pinia').mapActions
  const mapGetters: typeof import('pinia').mapGetters
  const mapState: typeof import('pinia').mapState
  const mapStores: typeof import('pinia').mapStores
  const mapWritableState: typeof import('pinia').mapWritableState
  const markRaw: typeof import('vue').markRaw
  const nextTick: typeof import('vue').nextTick
  const onActivated: typeof import('vue').onActivated
  const onBeforeMount: typeof import('vue').onBeforeMount
  const onBeforeRouteLeave: typeof import('vue-router').onBeforeRouteLeave
  const onBeforeRouteUpdate: typeof import('vue-router').onBeforeRouteUpdate
  const onBeforeUnmount: typeof import('vue').onBeforeUnmount
  const onBeforeUpdate: typeof import('vue').onBeforeUpdate
  const onDeactivated: typeof import('vue').onDeactivated
  const onErrorCaptured: typeof import('vue').onErrorCaptured
  const onMounted: typeof import('vue').onMounted
  const onRenderTracked: typeof import('vue').onRenderTracked
  const onRenderTriggered: typeof import('vue').onRenderTriggered
  const onScopeDispose: typeof import('vue').onScopeDispose
  const onServerPrefetch: typeof import('vue').onServerPrefetch
  const onUnmounted: typeof import('vue').onUnmounted
  const onUpdated: typeof import('vue').onUpdated
  const onWatcherCleanup: typeof import('vue').onWatcherCleanup
  const provide: typeof import('vue').provide
  const reactive: typeof import('vue').reactive
  const readonly: typeof import('vue').readonly
  const ref: typeof import('vue').ref
  const resolveComponent: typeof import('vue').resolveComponent
  const setActivePinia: typeof import('pinia').setActivePinia
  const setMapStoreSuffix: typeof import('pinia').setMapStoreSuffix
  const shallowReactive: typeof import('vue').shallowReactive
  const shallowReadonly: typeof import('vue').shallowReadonly
  const shallowRef: typeof import('vue').shallowRef
  const store: typeof import('./src/store/index.js').default
  const storeToRefs: typeof import('pinia').storeToRefs
  const toRaw: typeof import('vue').toRaw
  const toRef: typeof import('vue').toRef
  const toRefs: typeof import('vue').toRefs
  const toValue: typeof import('vue').toValue
  const triggerRef: typeof import('vue').triggerRef
  const unref: typeof import('vue').unref
  const useAttrs: typeof import('vue').useAttrs
  const useColumns: typeof import('./src/store/columns.js').useColumns
  const useCommon: typeof import('./src/store/common.js').useCommon
  const useCreateDesignOrderForms: typeof import('./src/store/init.js').useCreateDesignOrderForms
  const useCssModule: typeof import('vue').useCssModule
  const useCssVars: typeof import('vue').useCssVars
  const useDataStatsForms: typeof import('./src/store/init.js').useDataStatsForms
  const useDesignOrderDetail: typeof import('./src/store/init.js').useDesignOrderDetail
  const useDesignRateForms: typeof import('./src/store/init.js').useDesignRateForms
  const useEditPwdForms: typeof import('./src/store/init.js').useEditPwdForms
  const useGetSMSCodeForms: typeof import('./src/store/init.js').useGetSMSCodeForms
  const useI18n: typeof import('vue-i18n').useI18n
  const useId: typeof import('vue').useId
  const useInvoiceExportSearchForms: typeof import('./src/store/init.js').useInvoiceExportSearchForms
  const useInvoiceForms: typeof import('./src/store/init.js').useInvoiceForms
  const useInvoiceSearchForms: typeof import('./src/store/init.js').useInvoiceSearchForms
  const useInvoiceUpdateForms: typeof import('./src/store/init.js').useInvoiceUpdateForms
  const useLink: typeof import('vue-router').useLink
  const useLoginForms: typeof import('./src/store/init.js').useLoginForms
  const useModel: typeof import('vue').useModel
  const useOrderInfoDetail: typeof import('./src/store/init.js').useOrderInfoDetail
  const usePayOrderForms: typeof import('./src/store/init.js').usePayOrderForms
  const usePaymentOrderForms: typeof import('./src/store/init.js').usePaymentOrderForms
  const useQueryInvoiceInfo: typeof import('./src/store/init.js').useQueryInvoiceInfo
  const useQueryPlatWalletInfo: typeof import('./src/store/init.js').useQueryPlatWalletInfo
  const useQueryWalletInfo: typeof import('./src/store/init.js').useQueryWalletInfo
  const useRoute: typeof import('vue-router').useRoute
  const useRouter: typeof import('vue-router').useRouter
  const useSaveCityForms: typeof import('./src/store/init.js').useSaveCityForms
  const useSaveOrderForms: typeof import('./src/store/init.js').useSaveOrderForms
  const useSearchAccountInvoice: typeof import('./src/store/init.js').useSearchAccountInvoice
  const useSearchDesignOrderForms: typeof import('./src/store/init.js').useSearchDesignOrderForms
  const useSearchDesignStatisticsForms: typeof import('./src/store/init.js').useSearchDesignStatisticsForms
  const useSearchFactoryInfoForms: typeof import('./src/store/init.js').useSearchFactoryInfoForms
  const useSearchProcessingOrderForms: typeof import('./src/store/init.js').useSearchProcessingOrderForms
  const useSearchProcessingStatisticsForms: typeof import('./src/store/init.js').useSearchProcessingStatisticsForms
  const useSearchProductForms: typeof import('./src/store/init.js').useSearchProductForms
  const useSearchWalletForms: typeof import('./src/store/init.js').useSearchWalletForms
  const useSlots: typeof import('vue').useSlots
  const useTemplateRef: typeof import('vue').useTemplateRef
  const useUserBillDetail: typeof import('./src/store/init.js').useUserBillDetail
  const useUserPayPasswordForms: typeof import('./src/store/init.js').useUserPayPasswordForms
  const useWalletCashForms: typeof import('./src/store/init.js').useWalletCashForms
  const useWalletChargingForms: typeof import('./src/store/init.js').useWalletChargingForms
  const watch: typeof import('vue').watch
  const watchEffect: typeof import('vue').watchEffect
  const watchPostEffect: typeof import('vue').watchPostEffect
  const watchSyncEffect: typeof import('vue').watchSyncEffect
}
// for type re-export
declare global {
  // @ts-ignore
  export type { Component, Slot, Slots, ComponentPublicInstance, ComputedRef, DirectiveBinding, ExtractDefaultPropTypes, ExtractPropTypes, ExtractPublicPropTypes, InjectionKey, PropType, Ref, ShallowRef, MaybeRef, MaybeRefOrGetter, VNode, WritableComputedRef } from 'vue'
  import('vue')
}
